from __future__ import annotations

import argparse
from datetime import UTC, datetime
from pathlib import Path

import pandas as pd

from app.db.session import session_scope
from app.training.ablation_grid import AblationConfig, DistFamily, run_ablation

DEFAULT_REPORT_PATH = Path("reports/ablation_v1.md")
LOCKED_DEFAULTS_PATH = Path("app/training/locked_defaults.py")


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run Phase 4 ablation grid.")
    parser.add_argument("--seasons", default="2023", help="Comma-separated holdout seasons, e.g. 2023,2024")
    parser.add_argument("--configs", type=int, default=0, help="Run only first N configs (smoke mode).")
    parser.add_argument("--full", action="store_true", help="Run the full ablation grid.")
    return parser.parse_args()


def _build_config_grid(full: bool, limit: int) -> list[AblationConfig]:
    dist_values: list[DistFamily]
    if full:
        k_values = [2, 3, 4, 5, 6]
        l1_values = [0.0, 0.001, 0.005, 0.01]
        # `decomposed` remains available but is excluded from default grid until
        # its pathway diverges materially from legacy.
        dist_values = ["legacy", "count_aware"]
        feature_flag_sets = [frozenset()]
    else:
        k_values = [2, 4]
        l1_values = [0.0, 0.01]
        dist_values = ["legacy", "count_aware"]
        feature_flag_sets = [frozenset()]

    configs = [
        AblationConfig(k_seasons=k, l1_alpha=l1, dist_family=dist, feature_flags=flags)
        for k in k_values
        for l1 in l1_values
        for dist in dist_values
        for flags in feature_flag_sets
    ]
    if limit > 0:
        return configs[:limit]
    return configs


def _write_locked_defaults(best_overall: pd.Series, best_by_market: pd.DataFrame) -> None:
    k_seasons = int(best_overall["k_seasons"])
    l1_alpha = float(best_overall["l1_alpha"])
    market_defaults = {
        str(row["market_key"]): str(row["dist_family"])
        for row in best_by_market.to_dict("records")
    }
    lines = [
        "from __future__ import annotations",
        "",
        'from typing import Literal',
        "",
        'DistFamily = Literal["legacy", "count_aware", "decomposed"]',
        "",
        "# Auto-generated by scripts/run_ablation.py",
        f"DEFAULT_K_SEASONS = {k_seasons}",
        f"DEFAULT_L1_ALPHA = {l1_alpha}",
        'DEFAULT_DIST_FAMILY: DistFamily = "legacy"',
        "",
        "MARKET_DIST_FAMILY_DEFAULTS: dict[str, DistFamily] = {",
    ]
    for market_key in sorted(market_defaults):
        lines.append(f'    "{market_key}": "{market_defaults[market_key]}",')
    lines.append("}")
    LOCKED_DEFAULTS_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _write_report(
    path: Path,
    *,
    seasons: list[str],
    result: pd.DataFrame,
    best_overall: pd.Series,
    best_by_market: pd.DataFrame,
) -> None:
    timestamp = datetime.now(UTC).isoformat()
    avg_log_loss = float(result["log_loss"].mean()) if not result.empty else float("nan")
    lines = [
        "# Ablation Grid v1",
        "",
        f"- Generated at: {timestamp}",
        f"- Holdout seasons: {', '.join(seasons)}",
        f"- Config rows evaluated: {len(result)}",
        f"- Mean log_loss across rows: {avg_log_loss:.4f}",
        "",
        "## Locked defaults (current)",
        "",
        f"- k_seasons: {int(best_overall['k_seasons'])}",
        f"- l1_alpha: {float(best_overall['l1_alpha']):.6f}",
        "",
        "## Best dist family by market",
        "",
        "| Market | Dist Family | Log Loss |",
        "|---|---|---:|",
    ]
    for row in best_by_market.sort_values("market_key").to_dict("records"):
        lines.append(f"| {row['market_key']} | {row['dist_family']} | {float(row['log_loss']):.4f} |")
    lines.extend(
        [
            "",
            "## Honesty Note",
            "",
            "- These defaults are selected from holdout backtest metrics and should be revalidated after any major feature/data-source change.",
        ]
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    args = _parse_args()
    seasons = [part.strip() for part in str(args.seasons).split(",") if part.strip()]
    configs = _build_config_grid(full=bool(args.full), limit=max(0, int(args.configs)))
    print(f"Running ablation with {len(configs)} config(s) on seasons: {', '.join(seasons)}")
    with session_scope() as session:
        result = run_ablation(configs=configs, holdout_seasons=seasons, session=session)
    if result.empty:
        raise SystemExit("Ablation produced no rows; verify holdout seasons and historical dataset.")

    result = result.sort_values(["market_key", "log_loss", "expected_calibration_error"]).reset_index(drop=True)
    best_by_market = result.groupby("market_key", as_index=False).first()
    best_overall = (
        result.groupby(["k_seasons", "l1_alpha", "dist_family"], as_index=False)["log_loss"]
        .mean()
        .sort_values("log_loss")
        .iloc[0]
    )

    _write_locked_defaults(best_overall=best_overall, best_by_market=best_by_market)
    _write_report(
        DEFAULT_REPORT_PATH,
        seasons=seasons,
        result=result,
        best_overall=best_overall,
        best_by_market=best_by_market,
    )
    timestamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
    csv_path = Path("reports") / f"ablation_grid_{timestamp}.csv"
    csv_path.parent.mkdir(parents=True, exist_ok=True)
    result.to_csv(csv_path, index=False)
    print(f"Wrote {DEFAULT_REPORT_PATH} and {csv_path}")


if __name__ == "__main__":
    main()
